# docker-compose.dev.yml

services:
  bot-dev:
    container_name: telegram-bot-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      - .:/app
    depends_on:
      db-dev:
        condition: service_healthy
    restart: unless-stopped

  db-dev:
    container_name: mysql-dev
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3307"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./structure.sql:/docker-entrypoint-initdb.d/structure.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data_dev:
